### ISSUE TITLE
U-boot SPL power off after 7 seconds

### ISSUE THREAD

**Issue by khozaei** [eewiki/u-boot-patches#10]
The u-boot SPL working in falcon mode after flashing it using dfu-util and then `reset` the board, but when the board is set ON, the u-boot SPL showing following message and after 7 seconds the board automatically powering off.
```
U-Boot SPL 2019.07-rc4-dirty (Mar 27 2020 - 01:04:53 +0430)

DRA752-GP ES2.0

Trying to boot from MMC2_2

no pinctrl state for default mode

no pinctrl state for default mode

Loading Environment from MMC... OK
```
If I press `c` and set ON the board, it goes to u-boot and the board state is stable.
How to fix it?

**Comment by RobertCNelson** [comment]
@khozaei which board?

**Comment by khozaei** [comment]
AM5728 EVM

**Comment by RobertCNelson** [comment]
@khozaei see Page 3 of https://github.com/beagleboard/beagleboard-x15/blob/master/BEAGLEBOARD_X15_REV_B1.pdf

 "Insert wire here to enable use of the JTAG without boot image present. Otherwise board will power off."...

Regards,

**Comment by khozaei** [comment]
Thank you so much.

**Comment by RobertCNelson** [comment]
@khozaei it's a built-in safety feature, so the am57xx doesn't fry..
