### ISSUE TITLE
Purpose of these patches?

### ISSUE THREAD

**Issue by anbraten** [eewiki/u-boot-patches#13]
What is the purpose of these patches? Seems like they are adding support for capes and different boot modes.

## Context
I am trying to build my own BBB image. I started with using u-boot `v2021.04` and it booted quite fine. As I am trying to get the [CTAG-2.4 cape](https://github.com/ctag-fh-kiel/ctag-face-2-4) to work, I am wondering if I need to apply something like these patches? Following [this guide](https://forum.digikey.com/t/debian-getting-started-with-the-beaglebone-black/12967) I tried to use `v2019.04`, but had no success:

<details>
 <summary>Boot log of v2019.04</summary>
U-Boot SPL 2019.04-dirty (Jun 06 2021 - 10:17:20 +0000)
Trying to boot from MMC1
Loading Environment from EXT4... 
** Unable to use mmc 0:1 for loading the env **

U-Boot 2019.04-dirty (Jun 06 2021 - 10:17:20 +0000)

CPU  : AM335X-GP rev 2.1
I2C:   ready
DRAM:  512 MiB
No match for driver 'omap_hsmmc'
No match for driver 'omap_hsmmc'
Some drivers were not found
Reset Source: Power-on reset has occurred.
RTC 32KCLK Source: External.
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Loading Environment from EXT4... 
** Unable to use mmc 0:1 for loading the env **
Board: BeagleBone Black
<ethaddr> not set. Validating first E-fuse MAC
BeagleBone Black:
BeagleBone Cape EEPROM: no EEPROM at address: 0x54
BeagleBone Cape EEPROM: no EEPROM at address: 0x55
BeagleBone Cape EEPROM: no EEPROM at address: 0x56
BeagleBone Cape EEPROM: no EEPROM at address: 0x57
Net:   eth0: MII MODE
cpsw, usb_ether
Press SPACE to abort autoboot in 0 seconds
board_name=[A335BNLT] ...
board_rev=[000C] ...
switch to partitions #0, OK
mmc0 is current device
SD/MMC found on device 0
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
switch to partitions #0, OK
mmc0 is current device
gpio: pin 54 (gpio 54) value is 1
Checking for: /uEnv.txt ...
39 bytes read in 1 ms (38.1 KiB/s)
gpio: pin 55 (gpio 55) value is 1
Loaded environment from /uEnv.txt
Importing environment from mmc ...
Checking if uenvcmd is set ...
Checking if client_ip is set ...
Checking for: /boot.scr ...
Checking for: /boot/boot.scr ...
Checking for: /boot/uEnv.txt ...
** Invalid partition 3 **
** Invalid partition 4 **
** Invalid partition 5 **
** Invalid partition 6 **
** Invalid partition 7 **
switch to partitions #0, OK
mmc1(part 0) is current device
** Invalid partition 1 **
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
switch to partitions #0, OK
mmc1(part 0) is current device
gpio: pin 54 (gpio 54) value is 1
** Invalid partition 1 **
Checking for: /uEnv.txt ...
** Invalid partition 1 **
Checking for: /boot.scr ...
** Invalid partition 1 **
Checking for: /boot/boot.scr ...
** Invalid partition 1 **
Checking for: /boot/uEnv.txt ...
** Invalid partition 1 **
** Invalid partition 2 **
** Invalid partition 3 **
** Invalid partition 4 **
** Invalid partition 5 **
** Invalid partition 6 **
** Invalid partition 7 **
starting USB...
USB0:   Port not available.
</details>

Are there any plans to release a patch for `v2021.04`, etc. ?

**Comment by RobertCNelson** [comment]
> What is the purpose of these patches? Seems like they are adding support for capes and different boot modes.

Yes, that's exactly what the patches do....

> Loaded environment from /uEnv.txt
> Importing environment from mmc ...
> Checking if uenvcmd is set ...
> Checking if client_ip is set ...
> Checking for: /boot.scr ...
> Checking for: /boot/boot.scr ...
> Checking for: /boot/uEnv.txt ...

The guide specifcally talks about setting up: "/boot/uEnv.txt"  why are you using "/uEnv.txt" that's a legacy path..

Please dump your value of "/uEnv.txt"

> Are there any plans to release a patch for `v2021.04`, etc. ?

Nope..

I'm planning to upgrade to v2021.07 , as our cape overlay patches went mainline..

Regards,

**Comment by willeccles** [comment]
@RobertCNelson I'd like to tag on here instead of making a new issue. We are currently using the 2019.04 patches (and the corresponding u-boot version, of course) for our own custom hardware based on an OSD3358. While it's very handy that this exists, it does slightly obscure things for us. Given all I need is to boot from an [e]MMC device and have it load a device tree for the kernel, am I right in thinking it might be easier for me to restart and roll my own u-boot changes? As far as I can tell, the only major change that these make for us is the way it searches for a device tree in /boot/dtbs, but I'm not familiar enough to know how it would normally do this, either. A point in the right direction would be much appreciated. Thanks!

**Comment by RobertCNelson** [comment]
@willeccles eeprom value:

default pinmux:
https://github.com/u-boot/u-boot/blob/master/board/ti/am335x/mux.c#L369

default device-tree:
https://github.com/u-boot/u-boot/blob/master/configs/am335x_evm_defconfig#L5
https://github.com/u-boot/u-boot/blob/master/board/ti/am335x/board.c#L941

built-in device-tree
https://github.com/u-boot/u-boot/blob/master/configs/am335x_evm_defconfig#L40

pick kernel device tree

https://github.com/u-boot/u-boot/blob/master/include/configs/am335x_evm.h#L126-L150

**Comment by willeccles** [comment]
Thanks! I'll give it a shot.
