### ISSUE TITLE
U-Boot SPL ethernet support

### ISSUE THREAD

**Issue by gtortone** [eewiki/u-boot-patches#6]
Hi,

I was wondering if it is possible (as with AM335x) for AM5728 to compile a SPL that support network fetch of u-boot.img;

I did it with AM335x adding to file include/configs/ti_am335x_common.h:
# define CONFIG_SPL_ETH_SUPPORT
# define CONFIG_SPL_NET_SUPPORT

but I did not have success with AM5728 applying the same recipe on include/configs/am57xx_evm.h

I'm using ti-u-boot-2016.05 with this patch:

https://rcn-ee.com/repos/git/u-boot-patches/ti-2016.05/0001-beagle_x15-uEnv.txt-bootz-n-fixes.patch

I also launch these make to build U-Boot:

make ARCH=arm CROSS_COMPILE=${CC} distclean
make ARCH=arm CROSS_COMPILE=${CC} am57xx_evm_config
make ARCH=arm CROSS_COMPILE=${CC}

Thanks in advance,
Gennaro

**Comment by RobertCNelson** [comment]
@gtortone double check with mainline v2016.09 first, the am57xx/dra7 target is still relatively new, but the cpsw ip is just an extension of the am335x cpsw ip..

Regards,

**Comment by gtortone** [comment]
Thanks,
but do you refer to mainline U-Boot (https://github.com/u-boot/u-boot) or mainline TI-U-Boot (https://git.ti.com/ti-u-boot/ti-u-boot) ?

**Comment by RobertCNelson** [comment]
@gtortone pure mainline, https://github.com/u-boot/u-boot

**Comment by gtortone** [comment]
Same result:
u-boot.img build is ok, but u-boot-spl.bin fails with:
```
common/spl/built-in.o: In function `spl_net_load_image':
/home/tortone/devel/Belle2/BB-X15/testing/u-boot/common/spl/spl_net.c:21: undefined reference to `env_init'
common/built-in.o: In function `env_relocate':
/home/tortone/devel/Belle2/BB-X15/testing/u-boot/common/env_common.c:267: undefined reference to `env_relocate_spec'
common/built-in.o:(.data.env_htab+0xc): undefined reference to `env_flags_validate'
lib/built-in.o: In function `hsearch_r':
/home/tortone/devel/Belle2/BB-X15/testing/u-boot/lib/hashtable.c:380: undefined reference to `env_callback_init'
/home/tortone/devel/Belle2/BB-X15/testing/u-boot/lib/hashtable.c:382: undefined reference to `env_flags_init'
```

**Comment by wzj2346584** [comment]
lib/built-in.o: In function `hsearch_r':
/home/tortone/devel/Belle2/BB-X15/testing/u-boot/lib/hashtable.c:380: undefined reference to `env_callback_init'
/home/tortone/devel/Belle2/BB-X15/testing/u-boot/lib/hashtable.c:382: undefined reference to `env_flags_init'

how to sovle this ?

**Comment by RobertCNelson** [comment]
@wzj2346584 this thread should have been closed, can you please add more "context" of what you are building?

**Comment by wzj2346584** [comment]
lib/built-in.o: In function `hsearch_r':
/home/wzj/桌面/4b/rockchip-bsp/u-boot/lib/hashtable.c:381: undefined reference to `env_callback_init'
/home/wzj/桌面/4b/rockchip-bsp/u-boot/lib/hashtable.c:383: undefined reference to `env_flags_init'
env/built-in.o:(.data.env_htab+0x10): undefined reference to `env_flags_validate'
make[2]: *** [scripts/Makefile.spl:350：spl/u-boot-spl] 错误 1
make[1]: *** [Makefile:1405：spl/u-boot-spl] 错误 2
make: *** [Makefile:461：__build_one_by_one] 错误 2
 MAKE UBOOT IMAGE FAILED.



I want to add the uuid command ,so I add  "CONFIG_CMD_UUID=y" to the "rk339_defconfig" file. 
And then build the u-boot,   but the above error  appears.   
help!

**Comment by RobertCNelson** [comment]
@wzj2346584 please contact the developers behind that branch, I'm closing this thread.
